---
- hosts: localhost
  tags:
     - editors
     - vim
  connection: local
  roles:
     - dzordzu.ddf.vim

- hosts: localhost
  tags:
     - graphical
  connection: local
  roles:
     - dzordzu.ddf.polybar
     - dzordzu.ddf.i3
     - dzordzu.ddf.alacritty
     - dzordzu.ddf.picom

- hosts: localhost
  tags:
     - common
     - bin
  connection: local
  roles:
     - dzordzu.ddf.binaries

- hosts: localhost
  tags:
     - common
  connection: local
  roles:
     - dzordzu.ddf.export_vars
     - dzordzu.ddf.packages
     - dzordzu.ddf.cleaner

- hosts: localhost
  connection: local
  tags:
     - terminal
  roles:
     - dzordzu.ddf.zsh
     - dzordzu.ddf.tmux
