#!/bin/bash

# Shells config files (you're using)
# General config (like exports)
# is added to them
SHELLS=(zshrc bashrc cshrc profile)

# Set to any hostname you wish. 
# Empty value keeps your current hostname
HOSTNAME=

# Change to 1 in order to set up ONLY a
# connection with the master puppet node
# and prepare system basics via ansible
SLAVE_INSTALL=0
