#!/bin/sh

connection=$(pgrep -a openvpn$ | head -n 1 | awk '{print $NF }' | cut -d '.' -f 1)
connections_text="$(nmcli conn | grep vpn)"

IFS="\n" read -r -a connections_array <<< $connections_text
result=`awk '{ ORS=" "; ($4 != "--") ? res = "(vpn: " $1 ")" : res=""; print res}' <<< $connections_text`

echo "%{F#fcfaa7} $result"

