---
- name: Install ArchLinux packages
  when: ansible_distribution == 'Archlinux'
  include_tasks: "archlinux.yml"

- name: Create user dir ~/.config/polybar
  file:
    path: ~/.config/polybar
    state: directory

- name: Create ~/.config/polybar/config
  template:
    src: config.j2
    dest: ~/.config/polybar/config
    mode: '0644'
  tags:
    - "rc"
