---

- name: Install vim(s)
  become: false
  aur:
    name:
      - neovim
      - gvim
      - vim

- name: Install file navigation tools
  become: false
  aur:
    name:
      - ranger
      - fzf
      - tmux
      - ripgrep

# vim: ft=yaml.ansible
