---

- name: Install vim(s)
  become: false
  aur:
    name: "{{ item }}"
  with_items:
    - neovim
    - gvim
    - vim

- name: Install file navigation tools
  become: false
  aur:
    name: "{{ item }}"
  with_items:
    - ranger
    - fzf
    - tmux
    - ripgrep

# vim: ft=yaml.ansible
