---
- name: Install ArchLinux packages
  when: ansible_distribution == 'Archlinux'
  include_tasks: "archlinux.yml"

- name: Create user dir ~/.config/vim
  file:
    path: ~/.config/vim
    state: directory

- name: Create main.vimrc file
  file:
    path: ~/.config/vim/main.vimrc
    state: touch

- name: Install configuration
  template:
    src: vimrc.j2
    dest: ~/.vimrc
    mode: '0644'
  tags:
    - "rc"

- name: Create user dir ~/.config/nvim
  file:
    path: ~/.config/nvim
    state: directory

- name: Create main.vimrc file
  file:
    path: ~/.config/nvim/init.vim
    state: touch


- name: Install configuration
  template:
    src: vimrc.j2
    dest: ~/.config/nvim/init.vim
    mode: '0644'
  tags:
    - "rc"

- name: Install vim plugins
  command: "nvim -c :PlugUpdate -c :qa"
  tags:
    - "updates"

- name: UltiSnips update
  include_tasks:
    file: "ultisnips.yml"
    apply:
      tags:
        - "rc"
  tags:
    - "rc"


# vim: ft=yaml.ansible
