---

- name: Create ultisnips
  with_fileglob:
    - templates/ultisnips/*.snippets.j2
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/files/UltiSnips/
    {{ item | basename | regex_replace('\\.j2$', '') }}"


- name: Remove old ultisnips (vim)
  when: ddf_ultisnips_force
  file:
    state: absent
    path: ~/.config/nvim/UltiSnips

- name: Remove old ultisnips (nvim)
  when: ddf_ultisnips_force
  file:
    state: absent
    path: ~/.config/vim/UltiSnips

- name: Link ultisnips
  when: ddf_ultisnips_behaviour == 'link'
  block:
    - name: Link ultisnips to vim
      file:
        state: link
        src: "{{ playbook_dir }}/files/UltiSnips"
        dest: ~/.config/vim/UltiSnips

    - name: Link ultisnips to nvim
      file:
        state: link
        src: "{{ playbook_dir }}/files/UltiSnips"
        dest: ~/.config/nvim/UltiSnips

- name: Copy ultisnips
  when: ddf_ultisnips_behaviour == "copy"
  block:
    - name: Copy ultisnips to vim
      copy:
        src: "{{ playbook_dir }}/files/UltiSnips"
        dest: ~/.config/vim

    - name: Link ultisnips to nvim
      copy:
        src: "{{ playbook_dir }}/files/UltiSnips"
        dest: ~/.config/nvim
