---

ddf_polybar_colors:
  main: "#232628"
  secondary: "#fcfcfc"
  critical: "#fca0a7"
  warning: "#fcfaa7"
  improvement: "#a7a0fc"

ddf_polybar_fonts:
  dejavu:
    font: "DejaVuSerifMono"
    size: 9
    vertical_offset: 3
  fontawesome:
    name: "Font Awesome 6 Free Solid"
    size: 10
    vertical_offset: 3

ddf_polybar_modules:
  battery:
    battery: BAT0
    adapter: ADP1
    full-at: 98

ddf_polybar_bars:
  default:
    fonts:
      - dejavu
      - fontawesome
    props:
      height: 44
      padding:
        left: 5
        right: 2
      dim:
        value: 0.5
    left:
      - battery
      - volume
      - cpu
      - ram
      - temperature
    center:
      - date
    right:
      - i3
      - network

  network:
    left:
      - network_detailed
    right:
      - date
