---

ddf_i3_wallpaper: "logo.png"

ddf_i3_modes:
  - name: 'launch'
    binding: '$mod+Shift+l'
  - name: 'key'
    binding: '$mod+Shift+k'
  - name: 'system'
    binding: '$mod+Shift+s'
  - name: 'workspaces'
    binding: '$mod+Shift+w'

ddf_i3_xrandr: xrandr --output HDMI-A-0 --auto --above eDP
