version: '3'
services:
   gitlab:
      restart: always
      image: 'gitlab/gitlab-ce'
      ports:
         - "127.1.0.1:80:80"
      volumes:
         - "gitlab-config:/etc/gitlab"
         - "gitlab-logs:/var/gitlab/logs"
         - "gitlab-data:/var/opt/gitlab"
volumes:
    gitlab-config:
    gitlab-logs:
    gitlab-data:
