---
- hosts: localhost
  become: true
  vars:
    ntp_timezone: Europe/Warsaw
  roles:
    - geerlingguy.ntp
  tasks:
    - name: Install puppet
      package:
        name: puppet
        state: present
