#!/bin/bash
# Install alacritty 
yay --needed -Sy --noconfirm \
   alacritty \
   w3m

yay --needed -Sy --noconfirm \
   ansible \
   ansible-lint

# Install music player
# yay --needed -Sy --noconfirm \
#    mopidy-spotify \
#    mopidy-mpd \
#    mopidy-musicbox \
#    mopidy-youtube-git \
#    glava \
#    ncmpcpp \
#    cava 

# Install browser 
yay --needed -Sy --noconfirm \
   qutebrowser

# Install rofi
yay --needed -Sy --noconfirm \
   rofi-dmenu \
   bitwarden-rofi

# Install i3
yay --needed -Sy --noconfirm \
   i3-gaps \
   feh \
   libevent \
   lxqt-notificationd \
   i3lock \
   unclutter \
   perl-anyevent-i3 \
   xdotool

# Install polybar
yay --needed -Sy --noconfirm \
   polybar \
   termsyn-font \
   ttf-font-awesome

# Install vim
yay --needed -Sy --noconfirm \
   gvim \
   vim-plug \
   xclip \
   npm

npm install instant-markdown-d

# Install zsh
yay --needed -Sy --noconfirm \
   zsh \
   ruby-colorls \
   antibody \
   oh-my-zsh-git \
   screenfetch \
   neofetch \
   ripgrep \
   ripgrep-all \
   ranger \
   fzf

# Install tmux
yay --needed -Sy --noconfirm \
   hstr-git \
   tmux \
   powerline

# Network and minor
yay --needed -Sy --noconfirm \
   nmap \
   bind-utils \



git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

