#!/bin/bash

INSTALL_TYPE="$1"

# Get current directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# Prepare .config
mkdir -p ~/.config

# Install wallpapers
mkdir -p ~/Wallpapers/Package
cp -r $DIR/wallpapers/* ~/Wallpapers/Package/
if [ ! -f ~/Wallpapers/main ]; then
   echo "Setting wallpaper"
   cp ~/Wallpapers/Package/main ~/Wallpapers/main
fi

# Install i3
cp -rf $DIR/i3 ~/.config/

# Install alacritty
cp -rf $DIR/alacritty ~/.config

# Install tmux
cp -rf $DIR/tmux ~/.config
mv ~/.config/tmux/.tmux.conf ~/.tmux.conf

# Install zsh
cp -rf $DIR/zsh ~/.config
mv ~/.config/zsh/.zshrc ~/.zshrc
sed -i "1 a # Generated variables" ~/.zshrc
sed -i "2 a \ " ~/.zshrc

sed -i "2 a export DF_DIR=$DIR" ~/.zshrc

# Install polybar
ETH_INT=$(ip link | awk 'BEGIN {FS=": "} {print $2}' | grep "^en")
WL_INT=$(ip link | awk 'BEGIN {FS=": "} {print $2}' | grep "^wl")
TUN_INT=$(ip link | awk 'BEGIN {FS=": "} {print $2}' | grep "^tun")
cp -rf $DIR/polybar ~/.config
sed -i "s/????ETH????/$ETH_INT/g" ~/.config/polybar/modules/network.ini
sed -i "s/????WL????/$WL_INT/g" ~/.config/polybar/modules/network.ini
sed -i "s/????TUN????/$TUN_INT/g" ~/.config/polybar/modules/network.ini

# Install rofi
cp -rf $DIR/rofi ~/.config

# Install vim
cp -rf $DIR/vim ~/.config
mv ~/.config/vim/.vimrc ~/.vimrc

if [[ "$INSTALL_TYPE" == "full" ]]; then 
   vim +VimEnter +PlugInstall +PlugClean +qall
   
   cd ~/.vim/plugged/command-t/ruby/command-t/ext/command-t
   ruby extconf.rb
   make

   cd ~/.vim/plugged/YouCompleteMe
   python3 install.py --all
fi


# Install dunst
cp -rf $DIR/dunst ~/.config

# Install ncmpcpp and cava and glava
mkdir -p ~/.config/{ncmpcpp,cava,glava}
cp -rf $DIR/{ncmpcpp,cava,glava} ~/.config

# Apply changes
DISPLAY=:0 i3-msg reload
tmux source-file ~/.tmux.conf

